[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dotenv = { workspace = true }
serde = { workspace = true }

# Local dependencies
core = { path = "../core" }